// Platform-provided database client — do NOT edit this file manually.
// It is auto-managed by the AlgorithmShift platform.
//
// Database Settings (in .env.local):
//   ENABLE_DATABASE=true|false  - Toggle database on/off
//   DATABASE_URL=postgresql://... - Connection string (required when enabled)
//   DATABASE_TYPE=postgres       - Database type (only postgres supported for now)

import { Pool, types } from 'pg';

// pg returns DATE/TIMESTAMP/TIMESTAMPTZ columns as JS Date objects, but every
// generated Row type declares them as strings and pages render them inline in
// JSX — a Date object reaching React throws "Objects are not valid as a React
// child". Return the raw postgres text instead; code that needs a Date can
// still construct one with new Date(value).
types.setTypeParser(1082, (v) => v); // DATE
types.setTypeParser(1114, (v) => v); // TIMESTAMP
types.setTypeParser(1184, (v) => v); // TIMESTAMPTZ

// Check if database is enabled via environment variable
const isDbEnabled = process.env.ENABLE_DATABASE === 'true';
const hasDbUrl = !!process.env.DATABASE_URL;

// Determine if we should use real database or mock data
export const isMockMode = !isDbEnabled || !hasDbUrl;

// Only create pool if database is enabled and URL is provided
let _pool: Pool | null = null;
if (!isMockMode) {
  _pool = new Pool({
    connectionString: process.env.DATABASE_URL,
    // Detect any TLS-requested URL (new `no-verify`, legacy `require`,
    // or `verify-*` variants) and always pair with `rejectUnauthorized:
    // false`. This is a platform-managed client so matching the portable
    // "trust any cert" RDS convention is the right default.
    ssl: /sslmode=(require|no-verify|verify-ca|verify-full|prefer)/i.test(
      process.env.DATABASE_URL ?? ''
    )
      ? { rejectUnauthorized: false }
      : false,
  });
}

/**
 * Execute a parameterised SQL query and return rows.
 *
 * When database is disabled, falls back to mock data from lib/json.ts
 *
 * @example
 *   const rows = await query<{ id: string; name: string }>(
 *     'SELECT * FROM users WHERE active = $1', [true]
 *   );
 */
export async function query<T = Record<string, unknown>>(
  sql: string,
  params?: unknown[]
): Promise<T[]> {
  // If mock mode, delegate to JSON mock helper
  if (isMockMode) {
    const { query: mockQuery } = await import('./json');
    return mockQuery<T>(sql, params);
  }

  // Real database query
  if (!_pool) {
    throw new Error('Database pool not initialized. Check ENABLE_DATABASE and DATABASE_URL settings.');
  }

  const client = await _pool.connect();
  try {
    const result = await client.query(sql, params);
    return result.rows as T[];
  } finally {
    client.release();
  }
}

/**
 * Non-null pool export. Real-DB mode: the pg Pool. Mock mode: a shim whose
 * query() delegates to lib/json.ts (rows wrapped in { rows } to match pg's
 * QueryResult shape) so route code written against pool.query works without
 * a database; other pool methods throw with a clear message.
 *
 * The old export was `Pool | null` (null in mock mode), which broke the
 * documented contract ("pool.query delegates to lib/json in mock mode") at
 * runtime AND made every fresh no-database app fail tsc in the auth
 * bundle's files ('pool' is possibly 'null') — surfacing as "pre-existing
 * typecheck errors" on the very first build.
 */
const _mockPoolShim = {
  query: async (sql: string, params?: unknown[]) => {
    const { query: mockQuery } = await import('./json');
    const rows = await mockQuery(sql, params);
    return { rows, rowCount: rows.length, command: '', oid: 0, fields: [] };
  },
  connect: async () => {
    throw new Error(
      'No database configured (mock mode) — pool.connect() is unavailable. Use pool.query() or query().'
    );
  },
  end: async () => undefined,
} as unknown as Pool;

export const pool: Pool = _pool ?? _mockPoolShim;

// Log database mode on module load (server-side only)
if (typeof window === 'undefined') {
  console.log(`[db] Mode: ${isMockMode ? 'MOCK (using lib/json.ts)' : 'REAL (PostgreSQL)'}`);
  if (isMockMode && isDbEnabled && !hasDbUrl) {
    console.warn('[db] ENABLE_DATABASE=true but DATABASE_URL is missing!');
  }
}
